version: '3.4'
networks:
  mynetwork:
    driver: bridge

services:
  fullstack:
    image: fullstack:latest
    depends_on:
      - "postgres_image"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    # environment:
    #   DB_CONNECTION_STRING:"host:postgres_image;port=5432;database=fullstackdb;username=postgres;password=password"
    networks:
      - mynetwork

  postgres_image:
    image: postgres:latest
    ports:
      - "5432"
    restart: always
    volumes:
      - db_volume:/var/lib/postgresql/data
      #- ./dbscripts/seed.sql :/docker-entrypoint-initdb.d/seed.sql
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "fullstackdb"
    networks:
      - mynetwork

volumes:
  db_volume: